apiVersion: v1
kind: Service
metadata:
  name: phrase-service
  namespace: inspire
  labels:
    app: phrase-service
    slot: blue
spec:
  selector:
    app: phrase-service
    slot: blue
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
